name: flutter_native_web_plugin_example
description: Demonstrates how to use the flutter_native_web_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_web_plugin:
    path: ../


flutter:
  uses-material-design: true

